Basic/build.gradle
Updated build tools to latest available. Failed to build if starting samples from scratch.
@jraanamo
=> [IDA-944] Updated build tools to 23.0.2

Basic/src/main/java/com/indooratlas/android/sdk/examples/ListExamplesActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/imageview/ImageViewActivity.java, Basic/src/main/res/values/strings.xml
@jraanamo INSPECTOR-23 On ImageViewActivity, the floor plan is not loaded if no
permissions to write on the external storage have been granted.
=> Permission enforcement

Basic/src/main/java/com/indooratlas/android/sdk/examples/simple/SimpleActivity.java, Basic/src/main/res/layout/location_request_dialog.xml, Basic/src/main/res/values/strings.xml
IDA-2238 User may select fastest interval and shortest displacement
values for location updates. Values can be entered using a dialog. @jraanamo
=> Location request options

Basic/src/main/AndroidManifest.xml, Basic/src/main/java/com/indooratlas/android/sdk/examples/sharelocation/ShareLocationActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/sharelocation/channel/LocationChannel.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/sharelocation/channel/pubnub/PubNubLocationChannelImpl.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/sharelocation/view/MultiLocationMapView.java
Fixed bugs in shared location example (05) and simplified the code generally. @jraanamo @ikarjalaIA
=> Update share location

Basic/src/main/java/com/indooratlas/android/sdk/examples/mapsoverlay/MapsOverlayActivity.java, Basic/src/main/res/values/strings.xml
- also moved toasts to snackbar messages so that user has a chance to
read the content
@tonimakkonen
=> Enable platform location

Basic/build.gradle, Basic/src/main/AndroidManifest.xml, Basic/src/main/java/com/indooratlas/android/sdk/examples/background/BackgroundActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/background/LocationStore.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/background/LocationStoreService.java, Basic/src/main/res/layout/activity_background.xml, Basic/src/main/res/values/strings.xml, Basic/src/main/res/xml/filepaths.xml, build.gradle
Example demonstrating receiving location updates to an IntentService in the background. Uses IALocationManager#requestLocationUpdates(IALocationRequest, PendingIntent) from the 2.4.0-alpha release.
@jraanamo
=> Background mode example

Basic/build.gradle, Basic/src/main/AndroidManifest.xml, Basic/src/main/java/com/indooratlas/android/sdk/examples/geofence/GeofenceActivity.java, Basic/src/main/res/layout/activity_geofence.xml, Basic/src/main/res/values/strings.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
Updated IndoorAtlas Android SDK to version 2.5.1
Updated gradle version.
Added example for using geofences.
=> Add example for geofences

Basic/build.gradle, Basic/src/main/java/com/indooratlas/android/sdk/examples/geofence/GeofenceActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/googlemaps/MapsActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/imageview/ImageViewActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/mapsoverlay/MapsOverlayActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/sharelocation/ShareLocationActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/simple/SimpleActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/utils/ExampleUtils.java, Basic/src/main/res/layout/activity_geofence.xml, README.md, build.gradle
* Updated gradle version to 2.3.3
* Updated IndoorAtlas Android SDK to version 2.5.2
* Added sharing of session information(traceId) to examples
=> Update indooratlas SDK to 2.5.2

Basic/src/main/AndroidManifest.xml, Basic/src/main/java/com/indooratlas/android/sdk/examples/locationsettings/LocationSettingsActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/utils/ExampleUtils.java, Basic/src/main/res/layout/activity_location_settings.xml, Basic/src/main/res/values/strings.xml
Some checks from MC for reference
=> Inital settings sample code implementation

Basic/build.gradle, Basic/src/main/AndroidManifest.xml, Basic/src/main/java/com/indooratlas/android/sdk/examples/foregroundservice/ForegroundService.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/foregroundservice/MainActivity.java, Basic/src/main/res/values/strings.xml, build.gradle
Added example using IndoorAtlas positioning in the background with the aid of Androids foreground services. 
Foreground services are required in the newer Android OS version to force Android to keep the service alive.
=> Added example  using Android foreground service

Basic/build.gradle, Basic/src/main/java/com/indooratlas/android/sdk/examples/osmdroid/OpenStreetMapOverlay.java, Basic/src/main/res/values/strings.xml
- Update open street maps library versions
- Simplify application logic
- Handle permissions
- Add zoom gesture controls and copyright overlay
=> Open street map fix

Basic/src/main/java/com/indooratlas/android/sdk/examples/googlemaps/MapsActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/imageview/ImageViewActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/simple/SimpleActivity.java, Basic/src/main/res/layout/activity_simple.xml, Basic/src/main/res/values/config.xml
To prepare for SDK 3.0 beta release
=> Remove explicit floor plan IDs from examples

Basic/src/main/java/com/indooratlas/android/sdk/examples/osmdroid/OpenStreetMapOverlay.java
=> Fix onPause registerRegionListener -> unregisterRegionListener

Basic/src/main/java/com/indooratlas/android/sdk/examples/geofence/GeofenceMapsOverlayActivity.java
- Fix geofence radius computation
- Use consistent radius everywhere
- Catch SecurityException if permission not granted
=> Hotfix geofence radius computation

Basic/src/main/java/com/indooratlas/android/sdk/examples/imageview/BlueDotView.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/imageview/ImageViewActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/imageview/SmoothEstimate.java, README.md
* Implements smooth estimate animation (for functionality sharing)
* Adds heading listener
* Cleans up code.
=> Feature estimate animation

Basic/build.gradle, Basic/src/main/java/com/indooratlas/android/sdk/examples/foregroundservice/ForegroundService.java, gradle.properties
* The endpoint is specified in gradle.properties.
* Also changed the comment lines in that file to use `#` instead of `//`. This gives correct syntax
highlighting in Android Studio
=> Add example code for sending background locations to a 3rd party backend

Basic/src/main/java/com/indooratlas/android/sdk/examples/foregroundservice/ForegroundService.java
=> Fix foreground service example data reporting

Basic/build.gradle, Basic/src/main/AndroidManifest.xml, Basic/src/main/java/com/indooratlas/android/sdk/examples/systemgeofence/GeofenceReceiver.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/systemgeofence/MainActivity.java, Basic/src/main/res/layout/activity_system_geofence.xml, Basic/src/main/res/values/strings.xml
Added example showing how to toggling location service base on Geofencing with Google play service
=> Add geofence with google play service example

Basic/src/main/java/com/indooratlas/android/sdk/examples/imageview/ImageViewActivity.java
Remove left over scaling which was not taken into account in drawing, this already uses subsamplingimageview
=> Fix drawing bug in imageview

Basic/build.gradle, Basic/proguard-rules.pro, Basic/src/main/AndroidManifest.xml, Basic/src/main/java/com/indooratlas/android/sdk/examples/ListExamplesActivity.java
- update also targetSdkVersion to 31 and add BLUETOOTH_SCAN permission for Android 12+
- remove obsolete proguard rule
=> Update IndoorAtlas SDK to 3.5.5

Basic/src/main/java/com/indooratlas/android/sdk/examples/imageview/ImageViewActivity.java, Basic/src/main/java/com/indooratlas/android/sdk/examples/mapsoverlay/MapsOverlayActivity.java
Show also outdoor positions in indoor-outdoor example
=> Plot also outdoor locations

Basic/src/main/java/com/indooratlas/android/sdk/examples/mapsoverlay/MapsOverlayActivity.java, Basic/src/main/res/layout/activity_maps_rotate.xml
Also shows heading and bearing as separate arrows
=> rotate map according to IndoorAtlas heading 
